### ISSUE TITLE
missing pred_labels.npy

### ISSUE THREAD

**Issue by nanocm** [yueyu1030/Patron#2]
pred_labels.npy seems not to be contained in the google drive folder

when executing `python patron_sample.py --dataset agnews --k 50 --rho 0.01 --gamma 0.5 --beta 0.5`, in *Data Selection Pipeline*, error is throwed below:
```shell
Traceback (most recent call last):
  File "patron_sample.py", line 205, in <module>
    train_emb, train_prompt_pred, train_label = load_data(args.dataset, args.model, template_id = args.template)
  File "patron_sample.py", line 94, in load_data
    train_label = np.load(path + "pred_labels.npy")
  File "/home/chen/miniconda3/envs/patron/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'agnews/pred_labels.npy'

**Comment by yueyu1030** [comment]
Hi there,

Thanks for pointing this issue out! We checked our code and found that we actually didn't use this data in our experiments. We have removed this file in the updated code. 

Best,
Yue

**Comment by nanocm** [comment]
an asserntion should be removed or annotated, too
Could you please double check the pipeline in these READMEs. These code or shell commands provided can not work well without some modification.
Thanks a lot.

**Comment by yueyu1030** [comment]
We will double-check the scripts later and fix some bugs. Thanks for letting us know!
